Tg   binary upgrade, interpret data, fees rewards parameters
dydxprotocol/v4-documentation pull request #164
Opened 2024-04-03 19:20 UTC by TommyGarch

2024-04-03 20:49 UTC, jiajames approved these changes

2024-04-04 00:29 UTC, jaredvu commented on pages/getting_started/getting_started.json
change the name of this file to `_meta.json`

2024-04-04 00:30 UTC, jaredvu commented on pages/guides/orderbook_stream.md
> +Further, please ensure your full node binary is v3.0.1, or v4.0.1 when it becomes mandatory on April 8th (subject to governance vote).
nits:
* put version in backticks?
* Add year to date

2024-04-04 00:33 UTC, jaredvu commented on pages/trading/_meta.json
> -  "Rewards_and_Parameters": "Rewards, Fees and Parameters",
Is the associated .md deleted?

2024-04-04 00:34 UTC, jaredvu requested changes
small items to fix

2024-04-04 18:29 UTC, jiajames approved these changes

2024-04-04 18:37 UTC, jaredvu approved these changes

2024-04-04 20:25 UTC, merged